package org.goblinSlayerCharacterSheet.models.enums;

public enum TypeOfWeapons {
    LIGHT_ONE_HANDED_SWORD,
    LIGHT_ONE_HANDED_MACE,
    LIGHT_ONE_HANDED_AXE,
    HEAVY_ONE_HANDED_SWORD,
    HEAVY_ONE_HANDED_MACE,
    HEAVY_ONE_HANDED_AXE,
    TWO_HANDED_SWORD,
    TWO_HANDED_AXE,
    TWO_HANDED_MACE,
    LIGHT_SPEAR,
    HEAVY_SPEAR,
    STAFF,
    CLOSE_COMBAT,
    THROWING,
    BOW,
    CROSSBOW,
    FIREARMS,
    NONE
}
